# Alfred Bot Config file
[API]
    [API.Google]
        [API.Google.Common]
            path='config/google'
        [API.Google.GoogleTasks]
            [API.Google.GoogleTasks.CheckTasks]
                module='google_tasks'
                phrase='Check tasks'
                function='checkTasks'
            [API.Google.GoogleTasks.CheckTasksList]
                module='google_tasks'
                phrase='Check task list'
                function='checkTasks'
            [API.Google.GoogleTasks.CreateTask]
                module='google_tasks'
                phrase='Create Google Task'
                function='createGoogleTask'
        [API.Google.GoogleCalendar]
            [API.Google.GoogleCalendar.CheckCalendar]
                module='google_calendar'
                phrase='Check my calendar'
                function='checkCalendar'
            [API.Google.GoogleCalendar.CreateEvent]
                module='google_calendar'
                phrase='Create event'
                function='createEvent'

    [API.github_wrapper]
        [API.github_wrapper.Common]
            API_KEY=<YOUR_GITHUB_API_KEY>
        [API.github_wrapper.LastCommit]
            phrase='Check my last commmit'
            function='checkLastCommit'

[TelegramBot]
    API_KEY=<YOUR_TELEGRAMBOT_API_KEY>
[Miscellaneous]
    TESTING=false